protocol imap {
  mail_max_userip_connections = 40
  imap_idle_notify_interval = 2 mins
  # سازگاری با Outlook و Thunderbird روی آرشیوهای بزرگ
  imap_client_workarounds = delay-newmail tb-extra-mailbox-sep tb-lsub-flags
}

protocol pop3 {
  pop3_uidl_format = %{uidvalidity}.%{uid}
  pop3_client_workarounds = outlook-no-nuls oe-ns-eoh
}
